### PR TITLE
Foundation Themes: Minor Styling 

### PR DESCRIPTION
**Pull request by hitesh96db**

### CODE REVIEW

**Comment by hitesh96db** [comment]
I'm not so familiar with SCSS, but this should suffice ?

**Comment by nursix** [comment]
Yes, I'll take it from here.

**Comment by nursix** [comment]
I've retained the outer border for embedded components (though lighter), otherwise the subform gets sliced by the even/odd shadowing - and parametrized the background-color for the comments feed.

**Comment by hitesh96db** [comment]
:+1:
@nursix I can help with the migration from I to ICONS, I see plenty of them in models so I can start with those.

**Comment by nursix** [comment]
:D yeah - take it a little slower. I'm actually working on this (on a schedule) and need to keep an eye on progress so that it doesn't conflict (there are some icons that are case-specific, and require additional adjustments in the respective themes).

So maybe better step by step.

Let's split this up - you look at controllers/*.py and modules/templates, I look into modules/s3 and the remainder of modules/s3db.

**Comment by nursix** [comment]
...and be prepared for some stop-signs from me, because we do have active deployments that use custom icon strategies - and we must not break those (but rather go the extra mile and replace their custom strategies with the standard pattern).

**Comment by hitesh96db** [comment]
>Let's split this up - you look at controllers/*.py and modules/templates, I look into modules/s3 and the remainder of modules/s3db.

I'm assuming you sent this reply before seeing the PR ? - because I already started with s3db :P 
Do you want me to shift to modules/templates ?

**Comment by hitesh96db** [comment]
@nursix 
>Let's split this up - you look at controllers/*.py and modules/templates, I look into modules/s3 and the remainder of modules/s3db.

I'm assuming you sent this reply before seeing the PR( but the time tells me you saw the PR first ;) ) ? - because I already started with s3db :P 
Do you want me to shift to modules/templates ?

**Pull request merged**
